apiVersion: v1
kind: Service
metadata:
  name: {{ include "myapp.fullname" . }}
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
spec:
  type: {{ .values.service.type }}
  ports:
    - port: {{ .values.service.port }}
      targetPort: 80
  selector:
    app: {{ include "myapp.name" . }}
